# Copyright (C) 2025 Alessandro Santini
# SPDX-License-Identifier: MIT

"""
Waveform
================================

IMRPhenomTHM interface class for waveform generation.

..autoclass:: IMRPhenomTHM
    :members:
    :undoc-members:
    :show-inheritance:
"""
from functools import partial
from typing import Optional

import jax
import jax.numpy as jnp
from jaxtyping import Array

from phentax.core import (
    AmplitudeCoeffs,
    PhaseCoeffs,
    compute_amplitude_coeffs_22,
    compute_amplitude_coeffs_hm,
    compute_phase_coeffs_22,
    compute_phase_coeffs_hm,
    imr_amplitude,
    imr_phase,
)
from phentax.core.internals import DerivedParams, WaveformParams, compute_derived_params
from phentax.utils.config import setup_logging
from phentax.utils.utility import check_equal_bhs, mode_to_lm
from phentax.utils.ylm import spin_weighted_spherical_harmonic_all_modes

logger = setup_logging(__name__)

ALLOWED_POSITIVE_HMS = [21, 33, 44, 55]


class IMRPhenomTHM:
    """
    Class for generating multi-polar, aligned-spin IMRPhenomTHM waveforms.

    """

    def __init__(
        self,
        f_min: float = 1e-6,  # Initial frequency in Hz
        f_ref: float = 20.0,  # Reference frequency in Hz #todo: check with Aurora / tutorial
        t_low_fit: bool = True,  # Use default fit for t_low if True.
        higher_modes: Optional[Array | list | str] = "all",
        include_negative_modes: bool = True,
        # todo add time options. return interpolant / dense array / sparse array
    ):

        if t_low_fit:
            logger.info("Using default fit in t(f): t_low = - 0.012 * f^(-2.7)")
            self.t_low = 0.0  # will be set in get_time_of_frequency
        else:
            logger.info(f"Using default t_low = -1e9")
            self.t_low = -1e9

        if higher_modes is None:
            self.higher_modes = jnp.array([])
            logger.info("No higher modes will be included.")

            self.ells: Array = jnp.array([2])
            self.mms: Array = jnp.array([2])

            self.compute_amp_phase = partial(self._compute_h22, return_coeffs=False)  # type: ignore

        else:
            if isinstance(higher_modes, str) and higher_modes == "all":
                self.higher_modes = jnp.asarray(ALLOWED_POSITIVE_HMS)

            elif isinstance(higher_modes, (list, Array)):
                self.higher_modes = jnp.asarray(higher_modes)
            else:
                raise TypeError(
                    "higher_modes must be None, a list, an array, or 'all'."
                )
            logger.info(f"Including higher modes: {self.higher_modes}")

            self.compute_amp_phase = self._compute_all_modes  # type: ignore

            # extract ells and mms
            self.ells, self.mms = mode_to_lm(self.higher_modes)
            self.ells = jnp.concatenate([jnp.array([2]), self.ells])
            self.mms = jnp.concatenate([jnp.array([2]), self.mms])

        self.include_negative_modes = include_negative_modes

        if self.include_negative_modes:
            logger.info("Negative m modes will be generated by symmetry.")
            # add negative modes to ells and mms
            self.negative_ls = self.ells[self.mms != 0]
            self.negative_mms = -self.mms[self.mms != 0]

        else:
            logger.info("Negative m modes will NOT be included.")
            self.negative_ls = jnp.array([])
            self.negative_mms = jnp.array([])

    def _compute_h22(
        self, times: Array, dparams: DerivedParams, return_coeffs: bool = False
    ) -> (
        tuple[DerivedParams, Array, Array, PhaseCoeffs]
        | tuple[DerivedParams, Array, Array]
    ):
        """
        Compute amplitude and phase for the (2,2) mode.

        Parameters
        ----------
        times : Array
            Time array.
        dparams : DerivedParams
            Derived parameters of the binary.
        return_coeffs : bool, default False
            Whether to return phase coefficients along with amplitude and phase.

        Returns
        -------
        dparams : DerivedParams
            Updated derived parameters. The computation of the (2,2) mode may update some time or frequency related parameters.
        amplitude_22 : Array
            Amplitude array for the (2,2) mode.
        phase_22 : Array
            Phase array for the (2,2) mode.
        phase_coeffs : PhaseCoeffs, optional
            Phase coefficients for the (2,2) mode, returned if `return_coeffs` is True. This are required for the higher modes.
        """
        dparams, phase_coeffs = compute_phase_coeffs_22(dparams)
        amplitude_coeffs = compute_amplitude_coeffs_22(dparams, phase_coeffs)

        amplitude_22 = jnp.abs(
            imr_amplitude(
                times,
                dparams.eta,
                amplitude_coeffs,
                phase_coeffs,
            )
        )

        phase_22 = imr_phase(
            times,
            dparams.eta,
            phase_coeffs,
        )

        if (
            return_coeffs
        ):  # return also phase coeffs. this assumes it will be used for hm computation
            return dparams, amplitude_22[None, :], phase_22[None, :], phase_coeffs
        else:
            return dparams, amplitude_22[None, :], phase_22[None, :]

    def _compute_hm(
        self,
        mode: int | Array,
        times: Array,
        dparams: DerivedParams,
        phase_coeffs_22: PhaseCoeffs,
        phase_22: Array,
        equal_black_holes: bool,
    ) -> tuple[Array, Array]:
        """
        Compute amplitude and phase for a given higher mode (beyond 22).
        It sets odd-m modes to zero if equal mass/spin.

        Parameters
        ----------
        mode : int | Array
            The (l,m) mode to compute, encoded as lm (e.g., 21 for (2,1)).
        times : Array
            Time array.
        dparams : DerivedParams
            Derived parameters of the binary.
        phase_coeffs_22 : PhaseCoeffs
            Phase coefficients for the (2,2) mode.
        phase_22 : Array
            Phase array for the (2,2) mode.
        equal_black_holes : bool
            Whether the binary consists of equal mass and spin black holes.

        Returns
        -------
        amplitude_hm : Array
            Amplitude array for the higher mode.
        phase_hm : Array
            Phase array for the higher mode.
        """
        if equal_black_holes and (mode % 2 == 1):
            logger.debug(
                f"Setting mode {mode} to zero due to equal mass/spin symmetry."
            )
            n_times = times.shape[0]
            return jnp.zeros((1, n_times)), jnp.zeros((1, n_times))

        m = mode % 10

        amplitude_coeffs = compute_amplitude_coeffs_hm(dparams, phase_coeffs_22, mode)
        phase_coeffs = compute_phase_coeffs_hm(
            dparams,
            phase_coeffs_22,
            OmegaCutPNAMP=amplitude_coeffs.omegaCutPNAMP,
            PhiCutPNAMP=amplitude_coeffs.phiCutPNAMP,
            mode=mode,
        )

        amplitude_hm = imr_amplitude(
            times,
            dparams.eta,
            amplitude_coeffs,
            phase_coeffs_22,
        )

        phase_hm = (
            imr_phase(
                times,
                dparams.eta,
                phase_coeffs,
                phase_22=phase_22,
            )
            - phase_coeffs.phoff
            - phase_coeffs.phiref0 * m / 2.0
        )

        return amplitude_hm, phase_hm

    # @partial(jax.jit, static_argnames=['self'])
    def _compute_all_modes(
        self, times: Array, dparams: DerivedParams
    ) -> tuple[DerivedParams, Array, Array]:
        """
        Compute amplitude and phase for all modes: (2,2) and higher modes.

        Parameters
        ----------
        times : Array
            Time array.
        dparams : DerivedParams
            Derived parameters of the binary.

        Returns
        -------
        dparams : DerivedParams
            Updated derived parameters.
        all_amplitudes : Array
            Amplitude arrays for all modes, shape (Nmodes, Ntimes).
        all_phases : Array
            Phase arrays for all modes, shape (Nmodes, Ntimes).
        """

        dparams, amplitude_22, phase_22, phase_coeffs_22 = self._compute_h22(times, dparams, return_coeffs=True)  # type: ignore

        equal_black_holes = check_equal_bhs(dparams.eta, dparams.chi1, dparams.chi2)

        amplitude_hms, phase_hms = jax.vmap(
            lambda mode: self._compute_hm(mode, times, dparams, phase_coeffs_22[0], phase_22, equal_black_holes)  # type: ignore
        )(self.higher_modes)

        # now stack 22 with hms
        all_amplitudes = jnp.concatenate(
            [amplitude_22, amplitude_hms], axis=0
        )  # shape (Nmodes, Ntimes)
        all_phases = jnp.concatenate(
            [phase_22, phase_hms], axis=0
        )  # shape (Nmodes, Ntimes)

        return dparams, all_amplitudes, all_phases

    @jax.jit
    def combine_amp_phase(self, amplitudes: Array, phases: Array) -> Array:
        """
        Combine amplitude and phase into complex strain h = A * exp(-i * phi).

        Parameters
        ----------
        amplitudes : Array
            Amplitude arrays for all modes, shape (Nmodes, Ntimes).
        phases : Array
            Phase arrays for all modes, shape (Nmodes, Ntimes).
        Returns
        -------
        h_modes : Array
            Complex strain arrays for all modes, shape (Nmodes, Ntimes).
        """
        h_modes = amplitudes * jnp.exp(-1j * phases)
        return h_modes

    def generate_hlms(
        self,
        times: Array,
        dparams: DerivedParams,
    ) -> tuple[DerivedParams, Array]:
        """
        Generate complex strain h_lm for all modes.

        Parameters
        ----------
        times : Array
            Time array.
        dparams : DerivedParams
            Derived parameters of the binary.

        Returns
        -------
        dparams : DerivedParams
            Updated derived parameters.
        h_modes : Array
            Complex strain arrays for all modes, shape (Nmodes, Ntimes).
        """
        dparams, amplitudes, phases = self.compute_amp_phase(times, dparams)  # type: ignore
        h_lm = self.combine_amp_phase(amplitudes, phases)

        # build return array with negative modes if needed
        if self.include_negative_modes:
            h_lmm = (-1) ** self.negative_ls[:, None] * jnp.conj(h_lm)
            h_lm = jnp.concatenate([h_lm, h_lmm], axis=0)

        return dparams, h_lm

    def generate_polarizations(
        self,
        times: Array,
        dparams: DerivedParams,
    ) -> tuple[DerivedParams, Array, Array]:
        """
        Generate plus and cross polarizations from the computed modes.

        Parameters
        ----------
        times : Array
            Time array.
        dparams : DerivedParams
            Derived parameters of the binary.

        Returns
        -------
        dparams : DerivedParams
            Updated derived parameters.
        h_plus : Array
            Plus polarization strain.
        h_cross : Array
            Cross polarization strain.
        """
        dparams, h_lms = self.generate_hlms(times, dparams)

        y_lms = spin_weighted_spherical_harmonic_all_modes(
            dparams.inclination, jnp.pi / 2.0 - dparams.phi_ref, self.ells, self.mms
        )
        if self.include_negative_modes:
            y_lmms = spin_weighted_spherical_harmonic_all_modes(
                dparams.inclination,
                jnp.pi / 2.0 - dparams.phi_ref,
                self.negative_ls,
                self.negative_mms,
            )
            y_lms = jnp.concatenate([y_lms, y_lmms], axis=0)

        strain = jnp.sum(h_lms * y_lms, axis=0)
        h_plus = jnp.real(strain)
        h_cross = -jnp.imag(strain)

        h_plus, h_cross = self.rotate_by_polarization(h_plus, h_cross, dparams.psi)

        return (
            dparams,
            h_plus,
            h_cross,
        )  # todo: understand what to do with time array and dparams return

    @jax.jit
    def rotate_by_polarization(
        self,
        h_plus: Array,
        h_cross: Array,
        psi: float | Array,
    ) -> tuple[Array, Array]:
        """
        Rotate the plus and cross polarizations by the polarization angle psi.

        Parameters
        ----------
        h_plus : Array
            Plus polarization strain.
        h_cross : Array
            Cross polarization strain.
        psi : float | Array
            Polarization angle in radians.

        Returns
        -------
        h_plus_rotated : Array
            Rotated plus polarization strain.
        h_cross_rotated : Array
            Rotated cross polarization strain.
        """
        cos_2psi = jnp.cos(2.0 * psi)
        sin_2psi = jnp.sin(2.0 * psi)

        h_plus_rotated = h_plus * cos_2psi - h_cross * sin_2psi
        h_cross_rotated = h_plus * sin_2psi + h_cross * cos_2psi

        return h_plus_rotated, h_cross_rotated

    def _process_parameters(
        self,
        m1: float | Array,
        m2: float | Array,
        chi1z: float | Array,
        chi2z: float | Array,
        distance: float | Array,
        phif_ref: float | Array,
        f_ref: float | Array,
        f_min: float | Array,
        inclination: float | Array,
        psi: float | Array,
        delta_t: float | Array = 5.0,
        t_min: float | Array = jnp.nan,  # todo decide if here or in init
        t_ref: float | Array = jnp.nan,  # todo decide if here or in init
    ) -> DerivedParams:
        """
        Process input parameters and compute derived parameters.

        Parameters
        ----------
        m1 : float | Array
            Mass of the first black hole in solar masses.
        m2 : float | Array
            Mass of the second black hole in solar masses.
        chi1z : float | Array
            Dimensionless spin of the first black hole along the orbital angular momentum.
        chi2z : float | Array
            Dimensionless spin of the second black hole along the orbital angular momentum.
        distance : float | Array
            Luminosity distance to the binary in megaparsecs.
        phif_ref : float | Array
            Reference phase at frequency f_ref in radians.
        f_ref : float | Array
            Reference frequency in Hz.
        f_min : float | Array
            Minimum frequency in Hz.
        inclination : float | Array
            Inclination angle of the binary in radians.
        psi : float | Array
            Polarization angle in radians.
        delta_t : float | Array, default 5.0
            Time step for waveform generation in seconds.
        t_min : float | Array, default jnp.nan
            Minimum time for waveform generation in seconds. If NaN, will be set by the minimum frequency.
        t_ref : float | Array, default jnp.nan
            Reference time for waveform generation in seconds. If NaN, will be set by the reference frequency.
        """

        wf_params = WaveformParams(
            m1=m1,
            m2=m2,
            s1z=chi1z,
            s2z=chi2z,
            distance=distance,
            inclination=inclination,
            phi_ref=phif_ref,
            psi=psi,
            f_ref=f_ref,
            f_min=f_min,
        )

        Dparams = compute_derived_params(
            wf_params, delta_t=delta_t, t_low=self.t_low, t_min=t_min, t_ref=t_ref
        )
        return Dparams


if __name__ == "__main__":
    pass
