# Copyright (C) 2025 Alessandro Santini
# SPDX-License-Identifier: MIT

# Credits for the original implementations: Cecilio García Quirós

"""
Waveform
================================

IMRPhenomTHM interface class for waveform generation.
"""

from typing import Optional

import jax
import jax.numpy as jnp
from jaxtyping import Array

from phentax.core import (
    AmplitudeCoeffs,
    PhaseCoeffs,
    compute_amplitude_coeffs_22,
    compute_amplitude_coeffs_hm,
    compute_phase_coeffs_22,
    compute_phase_coeffs_hm,
    imr_amplitude,
    imr_phase,
)
from phentax.core.internals import WaveformParams, compute_waveform_params
from phentax.utils.coarse_graining import (
    estimate_adaptive_steps_from_T,
    generate_adaptive_grid,
    generate_uniform_grid,
    masked_evaluate,
)
from phentax.utils.config import setup_logging
from phentax.utils.constants import YRSID_SI
from phentax.utils.utility import check_equal_bhs, mass_to_second, mode_to_lm
from phentax.utils.ylm import (
    spin_weighted_spherical_harmonic,
    spin_weighted_spherical_harmonic_all_modes,
)

logger = setup_logging(__name__)

ALLOWED_POSITIVE_HMS = [21, 33, 44, 55]


class IMRPhenomTHM:
    """
    Class for generating multi-polar, aligned-spin IMRPhenomTHM waveforms.

    Parameters
    ----------
    higher_modes : Optional[Array | list | str], default "all"
        Higher modes to include beyond (2,2). Can be:
        - None: only (2,2) mode.
        - "all": include all allowed higher modes.
        - list or Array of integers: specific modes to include (e.g., [21, 33]). Only the positive m modes have to be specified.
    include_negative_modes : bool, default True
        Whether to include negative m modes by symmetry.
    coarse_grain : bool, default False
        Whether to use adaptive coarse-graining for time grid generation.
    t_low_fit : bool, default True
        Whether to use the default fit for t_low in t(f).
    atol : float, default 1e-12
        Absolute tolerance for the t(f) root finding.
    rtol : float, default 1e-12
        Relative tolerance for the t(f) root finding.
    T : float | None, default None
        Total observation time in seconds. If None, it will be set to 3 months.
    """

    def __init__(
        self,
        higher_modes: Optional[Array | list | str] = "all",
        include_negative_modes: bool = True,
        coarse_grain: bool = False,
        t_low_fit: bool = True,  # Use default fit for t_low if True.
        atol: float = 1e-12,
        rtol: float = 1e-12,
        T: float | None = None,
        # todo add time options. return interpolant / dense array / sparse array
    ):
        if higher_modes is None:
            self.higher_modes = jnp.array([])
            self.has_hm = False
            logger.debug("No higher modes will be included.")

            self.ells: Array = jnp.array([2], dtype=jnp.int32)
            self.mms: Array = jnp.array([2], dtype=jnp.int32)

        else:
            if isinstance(higher_modes, str) and higher_modes == "all":
                self.higher_modes = jnp.asarray(ALLOWED_POSITIVE_HMS)

            elif isinstance(higher_modes, (list, Array)):
                self.higher_modes = jnp.asarray(higher_modes)
            else:
                raise TypeError(
                    "higher_modes must be None, a list, an array, or 'all'."
                )
            logger.debug("Including higher modes: %s", self.higher_modes)
            self.has_hm = True
            self.odd_modes_mask = (self.higher_modes % 2 == 1)[:, None]

            # extract ells and mms
            self.ells, self.mms = mode_to_lm(self.higher_modes)
            self.ells = jnp.concatenate([jnp.array([2]), self.ells])
            self.mms = jnp.concatenate([jnp.array([2]), self.mms])

        self.include_negative_modes = include_negative_modes

        if self.include_negative_modes:
            logger.debug("Negative m modes will be generated by symmetry.")
            # add negative modes to ells and mms
            self.negative_ls = self.ells[self.mms != 0]
            self.negative_mms = -self.mms[self.mms != 0]

        else:
            logger.debug("Negative m modes will NOT be included.")
            self.negative_ls = jnp.array([])
            self.negative_mms = jnp.array([])

        self.coarse_grain = coarse_grain
        logger.debug("Coarse graining set to %s", self.coarse_grain)

        if t_low_fit:
            logger.debug("Using fit in t(f): t_low = - 0.015 * f^(-2.7)")
            self.t_low = 0.0  # will be set in get_time_of_frequency
        else:
            logger.debug("Using default t_low = -1e9 M in t(f).")
            self.t_low = -1e9

        self.atol = atol
        self.rtol = rtol

        if T is None:
            logger.debug("Total observation time not specified. Setting to 3 months.")
            self.T = 3.0 / 12.0 * YRSID_SI
        else:
            self.T = T

        # max_adaptive_steps will be lazily set on first call in
        # initial_processing based on (T, delta_t).
        self.max_adaptive_steps = None

    def __repr__(self):
        return (
            "IMRPhenomTHM(higher_modes=%s, include_negative_modes=%s, coarse_grain=%s, t_low=%s, atol=%s, rtol=%s, T=%s)"
            % (
                self.higher_modes,
                self.include_negative_modes,
                self.coarse_grain,
                self.t_low,
                self.atol,
                self.rtol,
                self.T,
            )
        )

    @property
    def max_adaptive_steps(self) -> Optional[int]:
        return self._max_adaptive_steps

    @max_adaptive_steps.setter
    def max_adaptive_steps(self, value: Optional[int] = None):
        if value is not None:
            logger.debug("Setting max_adaptive_steps to %d", value)
            self._max_adaptive_steps = value
        else:
            logger.debug("max_adaptive_steps will be set on first call based on T.")
            self._max_adaptive_steps = None

    @property
    def num_modes(self) -> int:
        """
        Total number of modes included in the waveform, including negative m modes if applicable.
        """
        num_positive_modes = len(self.higher_modes) + 1  # +1 for the (2,2) mode
        if self.include_negative_modes:
            num_negative_modes = len(self.negative_ls)
            return num_positive_modes + num_negative_modes
        else:
            return num_positive_modes

    @jax.jit(static_argnames="self")
    def _compute_coeffs_22(
        self,
        wf_params: WaveformParams,
    ) -> tuple[WaveformParams, AmplitudeCoeffs, PhaseCoeffs]:
        """
        Compute amplitude and phase coefficients for the (2,2) mode.
        This updates relevant derived parameters in wf_params, and sets the time array if not provided.

        Parameters
        ----------
        wf_params : WaveformParams
            Waveform parameters of the binary.
        Returns
        -------
        wf_params : WaveformParams
            Updated derived parameters.
        amplitude_coeffs : AmplitudeCoeffs
            Amplitude coefficients for the (2,2) mode.
        phase_coeffs : PhaseCoeffs
            Phase coefficients for the (2,2) mode.
        """
        wf_params, phase_coeffs = compute_phase_coeffs_22(wf_params)
        amplitude_coeffs = compute_amplitude_coeffs_22(wf_params, phase_coeffs)

        return wf_params, amplitude_coeffs, phase_coeffs

    @jax.jit(static_argnames="self")
    def _compute_amp_phase_22(
        self,
        times: Array,
        mask: Array,
        wf_params: WaveformParams,
        amplitude_coeffs: AmplitudeCoeffs,
        phase_coeffs: PhaseCoeffs,
    ) -> tuple[Array, Array]:
        """
        Compute amplitude and phase for the (2,2) mode.

        Parameters
        ----------
        times : Array
            Time array.
        mask : Array
            Boolean mask indicating valid time points.
        wf_params : WaveformParams
            Waveform parameters of the binary.
        amplitude_coeffs : AmplitudeCoeffs
            Amplitude coefficients for the (2,2) mode.
        phase_coeffs : PhaseCoeffs
            Phase coefficients for the (2,2) mode.

        Returns
        -------
        amplitude_22 : Array
            Amplitude array for the (2,2) mode.
        phase_22 : Array
            Phase array for the (2,2) mode.
        """

        amplitude_22 = jnp.abs(
            masked_evaluate(
                times,
                mask,
                lambda t: imr_amplitude(
                    t,
                    wf_params.eta,
                    amplitude_coeffs,
                    phase_coeffs,
                ),
            )
        )

        phase_22 = masked_evaluate(
            times,
            mask,
            lambda t: imr_phase(
                t,
                wf_params.eta,
                phase_coeffs,
            )
            - phase_coeffs.phoff
            - phase_coeffs.phiref0,
            fill_value=0.0,
        )

        return amplitude_22[None, :], phase_22[None, :]

    @jax.jit(static_argnames="self")
    def _compute_amp_phase_hm(
        self,
        mode: int | Array,
        times: Array,
        mask: Array,
        wf_params: WaveformParams,
        phase_coeffs_22: PhaseCoeffs,
        phase_22: Array,
    ) -> tuple[Array, Array]:
        """
        Compute amplitude and phase for a given higher mode (beyond 22).
        It sets odd-m modes to zero if equal mass/spin.

        Parameters
        ----------
        mode : int | Array
            The (l,m) mode to compute, encoded as lm (e.g., 21 for (2,1)).
        times : Array
            Time array.
        mask : Array
            Boolean mask indicating valid time points.
        wf_params : WaveformParams
            Waveform parameters of the binary.
        phase_coeffs_22 : PhaseCoeffs
            Phase coefficients for the (2,2) mode.
        phase_22 : Array
            Phase array for the (2,2) mode.

        Returns
        -------
        amplitude_hm : Array
            Amplitude array for the higher mode.
        phase_hm : Array
            Phase array for the higher mode.
        """

        m = mode % 10

        amplitude_coeffs = compute_amplitude_coeffs_hm(wf_params, phase_coeffs_22, mode)
        phase_coeffs = compute_phase_coeffs_hm(
            wf_params,
            phase_coeffs_22,
            OmegaCutPNAMP=amplitude_coeffs.omegaCutPNAMP,
            PhiCutPNAMP=amplitude_coeffs.phiCutPNAMP,
            mode=mode,
        )

        amplitude_hm = masked_evaluate(
            times,
            mask,
            lambda t: imr_amplitude(
                t,
                wf_params.eta,
                amplitude_coeffs,
                phase_coeffs_22,
            ),
        )

        def compute_scalar_phase(_t, _mask, _p22):
            return jax.lax.cond(
                _mask,
                lambda _: imr_phase(
                    _t,
                    wf_params.eta,
                    phase_coeffs,
                    phase_22=_p22,
                )
                - phase_coeffs.phoff
                - phase_coeffs.phiref0 * m / 2.0,
                lambda _: 0.0,
                operand=None,
            )

        phase_hm = jax.vmap(compute_scalar_phase)(
            times, mask, phase_22 + phase_coeffs_22.phoff + phase_coeffs_22.phiref0
        )  # avoid double counting phoff and phiref0 in the 22 mode

        return amplitude_hm, phase_hm

    def _compute_all_modes(
        self,
        times: Array,
        mask: Array,
        wf_params: WaveformParams,
        amplitude_coeffs_22: AmplitudeCoeffs,
        phase_coeffs_22: PhaseCoeffs,
    ) -> tuple[Array, Array]:
        """
        Compute amplitude and phase for all modes: (2,2) and higher modes.

        Parameters
        ----------
        times : Array
            Time array.
        mask : Array
            Boolean mask indicating valid time points.
        wf_params : WaveformParams
            Waveform parameters of the binary.
        amplitude_coeffs_22 : AmplitudeCoeffs
            Amplitude coefficients for the (2,2) mode.
        phase_coeffs_22 : PhaseCoeffs
            Phase coefficients for the (2,2) mode.

        Returns
        -------
        all_amplitudes : Array
            Amplitude arrays for all modes, shape (Nmodes, Ntimes).
        all_phases : Array
            Phase arrays for all modes, shape (Nmodes, Ntimes).
        """

        amplitude_22, phase_22 = self._compute_amp_phase_22(
            times, mask, wf_params, amplitude_coeffs_22, phase_coeffs_22
        )

        if not self.has_hm:
            return amplitude_22, phase_22

        amplitude_hms, phase_hms = jax.vmap(
            lambda mode: self._compute_amp_phase_hm(
                mode, times, mask, wf_params, phase_coeffs_22, phase_22[0]
            )
        )(self.higher_modes)

        equal_black_holes = check_equal_bhs(
            wf_params.m1, wf_params.m2, wf_params.chi1, wf_params.chi2
        )

        should_zero = self.odd_modes_mask & equal_black_holes

        # Apply the mask using jnp.where
        amplitude_hms = jnp.where(should_zero, 0.0, amplitude_hms)
        phase_hms = jnp.where(should_zero, 0.0, phase_hms)

        # now stack 22 with hms
        all_amplitudes = jnp.concatenate(
            [amplitude_22, amplitude_hms], axis=0
        )  # shape (Nmodes, Ntimes)
        all_phases = jnp.concatenate(
            [phase_22, phase_hms], axis=0
        )  # shape (Nmodes, Ntimes)

        return all_amplitudes, all_phases

    @jax.jit(static_argnames="self")
    def combine_amp_phase(self, amplitudes: Array, phases: Array) -> Array:
        """
        Combine amplitude and phase into complex strain :math:`h = A * e^{-i \\phi}`.

        Parameters
        ----------
        amplitudes : Array
            Amplitude arrays for all modes, shape (Nmodes, Ntimes).
        phases : Array
            Phase arrays for all modes, shape (Nmodes, Ntimes).
        Returns
        -------
        h_modes : Array
            Complex strain arrays for all modes, shape (Nmodes, Ntimes).
        """
        h_modes = amplitudes * jnp.exp(-1j * phases)
        return h_modes

    def compute_amp_phase(
        self,
        m1: float | Array,
        m2: float | Array,
        chi1z: float | Array,
        chi2z: float | Array,
        distance: float | Array,
        phi_ref: float | Array,
        f_ref: float | Array,
        f_min: float | Array,
        inclination: float,
        psi: float | Array,
        delta_t: float = 15.0,
        t_min: float = jnp.nan,
        t_ref: float = jnp.nan,
        T: float | None = None,
    ) -> tuple[WaveformParams, Array, Array, Array, Array]:
        """
        Generate amplitude and phase for all modes for a batch of binaries or a single input.

        Parameters
        ----------
        m1 : float | Array
            Mass of the first black hole in solar masses.
        m2 : float | Array
            Mass of the second black hole in solar masses.
        chi1z : float | Array
            Dimensionless spin of the first black hole along the orbital angular momentum.
        chi2z : float | Array
            Dimensionless spin of the second black hole along the orbital angular momentum.
        distance : float | Array
            Luminosity distance to the binary in megaparsecs.
        phi_ref : float | Array
            Reference phase at frequency f_ref in radians.
        f_ref : float | Array
            Reference frequency in Hz.
        f_min : float | Array
            Minimum frequency in Hz.
        inclination : float
            Inclination angle of the binary in radians.
        psi : float | Array
            Polarization angle in radians.
        delta_t : float, default 15.0
            Time step for waveform generation in seconds.
        t_min : float, default jnp.nan
            Minimum time for waveform generation in seconds. If NaN, will be set by the minimum frequency.
        t_ref : float, default jnp.nan
            Reference time for waveform generation in seconds. If NaN, will be set by the reference frequency.
        T : float | None, default None
            Total observation time in seconds. If set, it overrides the default value.
        Returns
        -------
        wf_params : WaveformParams
            Waveform parameters of the binary.
        times : Array
            Time array in seconds.
        mask : Array
            Boolean mask indicating valid time points.
        amplitudes : Array
            Amplitude arrays for all modes, shape (Nbinaries, Nmodes, Ntimes).
        phases : Array
            Phase arrays for all modes, shape (Nbinaries, Nmodes, Ntimes).
        """

        wf_params, times, mask, amplitude_coeffs_22, phase_coeffs_22 = (
            self.initial_processing(
                m1,
                m2,
                chi1z,
                chi2z,
                distance,
                phi_ref,
                f_ref,
                f_min,
                inclination,
                psi,
                delta_t,
                t_min,
                t_ref,
                T,  # override default total observation time
            )
        )
        amplitudes, phases = jax.vmap(self._compute_all_modes)(
            times,
            mask,
            wf_params,
            amplitude_coeffs_22,
            phase_coeffs_22,
        )  # shape (Nbinaries, Nmodes, Ntimes)

        return wf_params, times, mask, amplitudes, phases

    def compute_hlms(
        self,
        m1: float | Array,
        m2: float | Array,
        chi1z: float | Array,
        chi2z: float | Array,
        distance: float | Array,
        phi_ref: float | Array,
        f_ref: float | Array,
        f_min: float | Array,
        inclination: float,
        psi: float | Array,
        delta_t: float = 15.0,
        t_min: float = jnp.nan,
        t_ref: float = jnp.nan,
        T: float | None = None,
    ) -> tuple[Array, Array, Array]:
        """
        Generate complex strain :math:`h_{lm}` for all modes for a batch of binaries or a single input.

        Parameters
        ----------
        m1 : float | Array
            Mass of the first black hole in solar masses.
        m2 : float | Array
            Mass of the second black hole in solar masses.
        chi1z : float | Array
            Dimensionless spin of the first black hole along the orbital angular momentum.
        chi2z : float | Array
            Dimensionless spin of the second black hole along the orbital angular momentum.
        distance : float | Array
            Luminosity distance to the binary in megaparsecs.
        phi_ref : float | Array
            Reference phase at frequency f_ref in radians.
        f_ref : float | Array
            Reference frequency in Hz.
        f_min : float | Array
            Minimum frequency in Hz.
        inclination : float
            Inclination angle of the binary in radians.
        psi : float | Array
            Polarization angle in radians.
        delta_t : float, default 15.0
            Time step for waveform generation in seconds.
        t_min : float, default jnp.nan
            Minimum time for waveform generation in seconds. If NaN, will be set by the minimum frequency.
        t_ref : float, default jnp.nan
            Reference time for waveform generation in seconds. If NaN, will be set by the reference frequency.
        T : float | None, default None
            Total observation time in seconds. If sets, it overrides the default value.

        Returns
        -------
        times : Array
            Time array in seconds.
        mask : Array
            Boolean mask indicating valid time points.
        h_lms : Array
            Complex strain arrays for all modes, shape (Nbinaries, Nmodes, Ntimes).
        """

        wf_params, times, mask, amplitudes, phases = self.compute_amp_phase(
            m1,
            m2,
            chi1z,
            chi2z,
            distance,
            phi_ref,
            f_ref,
            f_min,
            inclination,
            psi,
            delta_t,
            t_min,
            t_ref,
            T,
        )

        h_lms = (
            self.combine_amp_phase(amplitudes, phases)
            * wf_params.amp_factor[:, None, None]
        )  #

        # compute negative m modes by symmetry
        if self.include_negative_modes:
            h_lmms = (-1) ** self.negative_ls[None, :, None] * jnp.conj(h_lms)
            h_lms = jnp.concatenate([h_lms, h_lmms], axis=1)

        times = mass_to_second(times, wf_params.total_mass)

        return times, mask, h_lms

    def compute_strain_components(
        self,
        m1: float | Array,
        m2: float | Array,
        chi1z: float | Array,
        chi2z: float | Array,
        distance: float | Array,
        phi_ref: float | Array,
        f_ref: float | Array,
        f_min: float | Array,
        inclination: float,
        psi: float | Array,
        delta_t: float = 15.0,
        t_min: float = jnp.nan,
        t_ref: float = jnp.nan,
        T: float | None = None,
    ) -> tuple[Array, Array, Array]:
        """
        Generate complex strain :math:`h_{lm}` for all modes and then multiply them by the corresponding spin-weighted spherical harmonics to get the contribution to the strain from each mode.

        Parameters
        ----------
        m1 : float | Array
            Mass of the first black hole in solar masses.
        m2 : float | Array
            Mass of the second black hole in solar masses.
        chi1z : float | Array
            Dimensionless spin of the first black hole along the orbital angular momentum.
        chi2z : float | Array
            Dimensionless spin of the second black hole along the orbital angular momentum.
        distance : float | Array
            Luminosity distance to the binary in megaparsecs.
        phi_ref : float | Array
            Reference phase at frequency f_ref in radians.
        f_ref : float | Array
            Reference frequency in Hz.
        f_min : float | Array
            Minimum frequency in Hz.
        inclination : float
            Inclination angle of the binary in radians.
        psi : float | Array
            Polarization angle in radians.
        delta_t : float, default 15.0
            Time step for waveform generation in seconds.
        t_min : float, default jnp.nan
            Minimum time for waveform generation in seconds. If NaN, will be set by the minimum frequency.
        t_ref : float, default jnp.nan
            Reference time for waveform generation in seconds. If NaN, will be set by the reference frequency.
        T : float | None, default None
            Total observation time in seconds. If sets, it overrides the default value.

        Returns
        -------
        times : Array
            Time array in seconds.
        mask : Array
            Boolean mask indicating valid time points.
        h_lms : Array
            Complex strain arrays for all modes, shape (Nbinaries, Nmodes, Ntimes).
        """
        times, mask, h_lms = self.compute_hlms(
            m1,
            m2,
            chi1z,
            chi2z,
            distance,
            phi_ref,
            f_ref,
            f_min,
            inclination,
            psi,
            delta_t,
            t_min,
            t_ref,
            T,
        )

        y_lms = spin_weighted_spherical_harmonic_all_modes(
            jnp.atleast_1d(inclination)[:, None],
            jnp.pi / 2.0 - jnp.atleast_1d(phi_ref)[:, None],
            self.ells,
            self.mms,
        )
        if self.include_negative_modes:
            y_lmms = spin_weighted_spherical_harmonic_all_modes(
                jnp.atleast_1d(inclination)[:, None],
                jnp.pi / 2.0 - jnp.atleast_1d(phi_ref)[:, None],
                self.negative_ls,
                self.negative_mms,
            )
            y_lms = jnp.concatenate([y_lms, y_lmms], axis=1)

        strain_components = h_lms * y_lms

        return times, mask, strain_components

    def compute_strain_components_amp_phase(
        self,
        m1: float | Array,
        m2: float | Array,
        chi1z: float | Array,
        chi2z: float | Array,
        distance: float | Array,
        phi_ref: float | Array,
        f_ref: float | Array,
        f_min: float | Array,
        inclination: float,
        psi: float | Array,
        delta_t: float = 15.0,
        t_min: float = jnp.nan,
        t_ref: float = jnp.nan,
        T: float | None = None,
    ) -> tuple[Array, Array, Array, Array]:
        """
        Generate complex strain :math:`h_{lm}` for all modes, and multiply them by the corresponding spin-weighted spherical harmonics to get the contribution to the strain from each mode.
        Extract the amplitude and phase of each mode.

        Parameters
        ----------
        m1 : float | Array
            Mass of the first black hole in solar masses.
        m2 : float | Array
            Mass of the second black hole in solar masses.
        chi1z : float | Array
            Dimensionless spin of the first black hole along the orbital angular momentum.
        chi2z : float | Array
            Dimensionless spin of the second black hole along the orbital angular momentum.
        distance : float | Array
            Luminosity distance to the binary in megaparsecs.
        phi_ref : float | Array
            Reference phase at frequency f_ref in radians.
        f_ref : float | Array
            Reference frequency in Hz.
        f_min : float | Array
            Minimum frequency in Hz.
        inclination : float
            Inclination angle of the binary in radians.
        psi : float | Array
            Polarization angle in radians.
        delta_t : float, default 15.0
            Time step for waveform generation in seconds.
        t_min : float, default jnp.nan
            Minimum time for waveform generation in seconds. If NaN, will be set by the minimum frequency.
        t_ref : float, default jnp.nan
            Reference time for waveform generation in seconds. If NaN, will be set by the reference frequency.
        T : float | None, default None
            Total observation time in seconds. If sets, it overrides the default value.

        Returns
        -------
        times : Array
            Time array in seconds.
        mask : Array
            Boolean mask indicating valid time points.
        amplitudes : Array
            Amplitude arrays for all modes, shape (Nbinaries, Nmodes, Ntimes).
        phases : Array
            Phase arrays for all modes, shape (Nbinaries, Nmodes, Ntimes).
        """
        times, mask, strain_components = self.compute_strain_components(
            m1,
            m2,
            chi1z,
            chi2z,
            distance,
            phi_ref,
            f_ref,
            f_min,
            inclination,
            psi,
            delta_t,
            t_min,
            t_ref,
            T,
        )

        amplitudes = jnp.abs(strain_components)
        phases = jnp.unwrap(jnp.angle(strain_components))

        return times, mask, amplitudes, phases

    def compute_polarizations(
        self,
        m1: float | Array,
        m2: float | Array,
        chi1z: float | Array,
        chi2z: float | Array,
        distance: float | Array,
        phi_ref: float | Array,
        f_ref: float | Array,
        f_min: float | Array,
        inclination: float,
        psi: float | Array,
        delta_t: float = 15.0,
        t_min: float = jnp.nan,
        t_ref: float = jnp.nan,
        T: float | None = None,
    ) -> tuple[Array, Array, Array, Array]:
        """
        Generate plus and cross polarizations from the computed modes.

        Parameters
        ----------
        m1 : float | Array
            Mass of the first black hole in solar masses.
        m2 : float | Array
            Mass of the second black hole in solar masses.
        chi1z : float | Array
            Dimensionless spin of the first black hole along the orbital angular momentum.
        chi2z : float | Array
            Dimensionless spin of the second black hole along the orbital angular momentum.
        distance : float | Array
            Luminosity distance to the binary in megaparsecs.
        phi_ref : float | Array
            Reference phase at frequency f_ref in radians.
        f_ref : float | Array
            Reference frequency in Hz.
        f_min : float | Array
            Minimum frequency in Hz.
        inclination : float
            Inclination angle of the binary in radians.
        psi : float | Array
            Polarization angle in radians.
        delta_t : float, default 15.0
            Time step for waveform generation in seconds.
        t_min : float, default jnp.nan
            Minimum time for waveform generation in seconds. If NaN, will be set by the minimum frequency.
        t_ref : float, default jnp.nan
            Reference time for waveform generation in seconds. If NaN, will be set by the reference frequency.
        T : float | None, default None
            Total observation time in seconds. If sets, it overrides the default value.

        Returns
        -------
        times : Array
            Time array in seconds.
        mask : Array
            Boolean mask indicating valid time points.
        h_plus : Array
            Plus polarization strain.
        h_cross : Array
            Cross polarization strain.
        """
        times, mask, strain_components = self.compute_strain_components(
            m1,
            m2,
            chi1z,
            chi2z,
            distance,
            phi_ref,
            f_ref,
            f_min,
            inclination,
            psi,
            delta_t,
            t_min,
            t_ref,
            T,
        )

        # breakpoint()
        strain = jnp.sum(strain_components, axis=1)
        h_plus = jnp.real(strain)
        h_cross = -jnp.imag(strain)

        h_plus, h_cross = self.rotate_by_polarization_angle(h_plus, h_cross, psi)

        return times, mask, h_plus, h_cross

    # Define the single-binary computation to be vmapped
    @jax.jit(static_argnames="self")
    def _compute_strain_single(
        self,
        _times,
        _mask,
        _wf_params,
        _amp_coeffs_22,
        _phase_coeffs_22,
        _inc,
        _phi_ref,
    ):
        # 1. Compute (2,2) mode
        amp22, phase22 = self._compute_amp_phase_22(
            _times, _mask, _wf_params, _amp_coeffs_22, _phase_coeffs_22
        )
        # Remove singleton dim (1, Ntimes) -> (Ntimes,)
        amp22 = amp22[0]
        phase22 = phase22[0]

        h22 = amp22 * jnp.exp(-1j * phase22) * _wf_params.amp_factor

        # Project (2,2)
        # spin_weighted_spherical_harmonic takes (theta, phi, l, m)
        # phi for Ylm is usually pi/2 - phi_ref
        y22 = spin_weighted_spherical_harmonic(_inc, jnp.pi / 2.0 - _phi_ref, 2, 2)
        strain = h22 * y22

        if self.include_negative_modes:
            # Add (2,-2)
            # h(2,-2) = (-1)^2 * conj(h(2,2)) = conj(h22)
            y2m2 = spin_weighted_spherical_harmonic(
                _inc, jnp.pi / 2.0 - _phi_ref, 2, -2
            )
            strain += jnp.conj(h22) * y2m2

        if not self.has_hm:
            return strain

        # 2. Loop over higher modes
        n_modes = self.higher_modes.shape[0]

        # Pre-compute equal BH check for this binary
        equal_bhs = check_equal_bhs(
            _wf_params.m1, _wf_params.m2, _wf_params.chi1, _wf_params.chi2
        )

        def body_fun(i, current_strain):
            mode = self.higher_modes[i]

            # Compute HM waveform
            amp_hm, phase_hm = self._compute_amp_phase_hm(
                mode, _times, _mask, _wf_params, _phase_coeffs_22, phase22
            )

            # Apply odd-m masking for equal BHs
            m_mode = mode % 10
            is_odd = (m_mode % 2) == 1
            should_zero = is_odd & equal_bhs

            amp_hm = jnp.where(should_zero, 0.0, amp_hm)
            phase_hm = jnp.where(should_zero, 0.0, phase_hm)

            h_hm = amp_hm * jnp.exp(-1j * phase_hm) * _wf_params.amp_factor

            # Project (l, m)
            l_mode = mode // 10
            y_lm = spin_weighted_spherical_harmonic(
                _inc, jnp.pi / 2.0 - _phi_ref, l_mode, m_mode
            )
            term = h_hm * y_lm

            if self.include_negative_modes:
                # Add (l, -m)
                # h(l,-m) = (-1)^l * conj(h(l,m))
                y_lmm = spin_weighted_spherical_harmonic(
                    _inc, jnp.pi / 2.0 - _phi_ref, l_mode, -m_mode
                )
                # (-1)^l is 1.0 if l even, -1.0 if l odd
                parity = jnp.where(l_mode % 2 == 0, 1.0, -1.0)
                term += parity * jnp.conj(h_hm) * y_lmm

            return current_strain + term

        strain = jax.lax.fori_loop(0, n_modes, body_fun, strain)
        return strain

    def compute_polarizations_at_once(
        self,
        m1: float | Array,
        m2: float | Array,
        chi1z: float | Array,
        chi2z: float | Array,
        distance: float | Array,
        phi_ref: float | Array,
        f_ref: float | Array,
        f_min: float | Array,
        inclination: float,
        psi: float | Array,
        delta_t: float = 15.0,
        t_min: float = jnp.nan,
        t_ref: float = jnp.nan,
        T: float | None = None,
    ) -> tuple[Array, Array, Array, Array]:
        """
        Generate plus and cross polarizations, but computing the :math:`h_{lm}` individually for each mode to save memory.

        Parameters
        ----------
        m1 : float | Array
            Mass of the first black hole in solar masses.
        m2 : float | Array
            Mass of the second black hole in solar masses.
        chi1z : float | Array
            Dimensionless spin of the first black hole along the orbital angular momentum.
        chi2z : float | Array
            Dimensionless spin of the second black hole along the orbital angular momentum.
        distance : float | Array
            Luminosity distance to the binary in megaparsecs.
        phi_ref : float | Array
            Reference phase at frequency f_ref in radians.
        f_ref : float | Array
            Reference frequency in Hz.
        f_min : float | Array
            Minimum frequency in Hz.
        inclination : float
            Inclination angle of the binary in radians.
        psi : float | Array
            Polarization angle in radians.
        delta_t : float, default 15.0
            Time step for waveform generation in seconds.
        t_min : float, default jnp.nan
            Minimum time for waveform generation in seconds. If NaN, will be set by the minimum frequency.
        t_ref : float, default jnp.nan
            Reference time for waveform generation in seconds. If NaN, will be set by the reference frequency.
        T : float | None, default None
            Total observation time in seconds. If set, it overrides the default value.

        Returns
        -------
        times_out : Array
            Time array in seconds.
        mask_out : Array
            Boolean mask indicating valid time points.
        h_plus_out : Array
            Plus polarization strain.
        h_cross_out : Array
            Cross polarization strain.
        """

        wf_params, times, mask, amplitude_coeffs_22, phase_coeffs_22 = (
            self.initial_processing(
                m1,
                m2,
                chi1z,
                chi2z,
                distance,
                phi_ref,
                f_ref,
                f_min,
                inclination,
                psi,
                delta_t,
                t_min,
                t_ref,
                T,
            )
        )

        strain = jnp.zeros_like(times, dtype=jnp.complex128)

        # Vmap over the batch of parameters
        strain = jax.vmap(self._compute_strain_single)(
            times,
            mask,
            wf_params,
            amplitude_coeffs_22,
            phase_coeffs_22,
            wf_params.inclination,
            wf_params.phi_ref,
        )

        # Compute polarizations
        h_plus = jnp.real(strain)
        h_cross = -jnp.imag(strain)

        # Rotate by polarization angle psi
        h_plus, h_cross = self.rotate_by_polarization_angle(
            h_plus, h_cross, wf_params.psi
        )

        # Convert times to seconds
        times_sec = mass_to_second(times, wf_params.total_mass)

        return times_sec, mask, h_plus, h_cross

    @jax.jit(static_argnames="self")
    def rotate_by_polarization_angle(
        self,
        h_plus: Array,
        h_cross: Array,
        psi: float | Array,
    ) -> tuple[Array, Array]:
        """
        Rotate the plus and cross polarizations by the polarization angle :math:`\\psi`.

        Parameters
        ----------
        h_plus : Array
            Plus polarization strain.
        h_cross : Array
            Cross polarization strain.
        psi : float | Array
            Polarization angle in radians.

        Returns
        -------
        h_plus_rotated : Array
            Rotated plus polarization strain.
        h_cross_rotated : Array
            Rotated cross polarization strain.
        """
        cos_2psi = jnp.atleast_1d(jnp.cos(2.0 * jnp.array(psi)))[:, None]
        sin_2psi = jnp.atleast_1d(jnp.sin(2.0 * jnp.array(psi)))[:, None]

        h_plus_rotated = h_plus * cos_2psi - h_cross * sin_2psi
        h_cross_rotated = h_plus * sin_2psi + h_cross * cos_2psi

        return h_plus_rotated, h_cross_rotated

    @jax.jit(static_argnames="self")
    def _process_parameters(
        self,
        m1: float | Array,
        m2: float | Array,
        chi1z: float | Array,
        chi2z: float | Array,
        distance: float | Array,
        phi_ref: float | Array,
        f_ref: float | Array,
        f_min: float | Array,
        inclination: float | Array,
        psi: float | Array,
        delta_t: float | Array = 15.0,
        t_min: float | Array = jnp.nan,
        t_ref: float | Array = jnp.nan,
    ) -> WaveformParams:
        """
        Process input parameters and compute derived parameters.
        Convert all source parameters to arrays to enable batching.

        Parameters
        ----------
        m1 : float | Array
            Mass of the first black hole in solar masses.
        m2 : float | Array
            Mass of the second black hole in solar masses.
        chi1z : float | Array
            Dimensionless spin of the first black hole along the orbital angular momentum.
        chi2z : float | Array
            Dimensionless spin of the second black hole along the orbital angular momentum.
        distance : float | Array
            Luminosity distance to the binary in megaparsecs.
        phi_ref : float | Array
            Reference phase at frequency f_ref in radians.
        f_ref : float | Array
            Reference frequency in Hz.
        f_min : float | Array
            Minimum frequency in Hz.
        inclination : float | Array
            Inclination angle of the binary in radians.
        psi : float | Array
            Polarization angle in radians.
        delta_t : float | Array, default 5.0
            Time step for waveform generation in seconds.
        t_min : float | Array, default jnp.nan
            Minimum time for waveform generation in seconds. If NaN, will be set by the minimum frequency.
        t_ref : float | Array, default jnp.nan
            Reference time for waveform generation in seconds. If NaN, will be set by the reference frequency.

        Returns
        -------
        wf_params : WaveformParams
            Waveform parameters of the binary, including derived parameters like total mass, symmetric mass ratio,
            and time arrays.
        """

        wf_params = compute_waveform_params(
            m1=jnp.atleast_1d(m1),
            m2=jnp.atleast_1d(m2),
            s1z=jnp.atleast_1d(chi1z),
            s2z=jnp.atleast_1d(chi2z),
            distance=jnp.atleast_1d(distance),
            inclination=jnp.atleast_1d(inclination),
            phi_ref=jnp.atleast_1d(phi_ref),
            psi=jnp.atleast_1d(psi),
            f_ref=f_ref,
            f_min=f_min,
            delta_t=delta_t,
            t_min=t_min,
            t_ref=t_ref,
            t_low=self.t_low,
            atol=self.atol,
            rtol=self.rtol,
        )

        return wf_params

    def get_time_grids(
        self,
        wf_params: WaveformParams,
        num_steps: int,
    ) -> tuple[Array, Array]:
        """
        Generate the time grid for waveform generation based on waveform parameters.

        Parameters
        ----------
        wf_params : WaveformParams
            Waveform parameters of the binary.
        num_steps : int
            Number of steps for the time grid. This is used to allocate memory for the time grid,
            and it ensures all the binaries in the batch have the same number of steps.

        Returns
        -------
        times : Array
            Time array in units of mass for waveform generation.
        mask : Array
            Boolean mask indicating valid time points.
        """

        if self.coarse_grain:
            # Use the pre-computed worst-case max_steps so the JIT-compiled
            # grid generator is never recompiled due to parameter changes.
            if self.max_adaptive_steps is None:
                raise RuntimeError(
                    "Adaptive grid size not initialized. "
                    "This should not happen — please report a bug."
                )

            # Clamp Mt_min so the adaptive grid doesn't extend beyond Tobs.
            # num_steps * Mdelta_t = T/M = Tobs in mass units.
            Mt_min_obs = jnp.maximum(
                wf_params.Mt_min,
                wf_params.Mt_end - num_steps * wf_params.Mdelta_t,
            )

            times, mask = generate_adaptive_grid(
                wf_params.eta,
                Mt_min_obs,
                wf_params.Mt_end,
                wf_params.Mdelta_t,
                max_steps=self.max_adaptive_steps,
            )

        else:
            times, mask = generate_uniform_grid(
                wf_params.Mt_min,
                wf_params.Mt_end,
                wf_params.Mdelta_t,
                max_steps=num_steps,
            )

        return times, mask

    def initial_processing(
        self,
        m1: float | Array,
        m2: float | Array,
        chi1z: float | Array,
        chi2z: float | Array,
        distance: float | Array,
        phi_ref: float | Array,
        f_ref: float | Array,
        f_min: float | Array,
        inclination: float | Array,
        psi: float | Array,
        delta_t: float | Array = 15.0,
        t_min: float | Array = jnp.nan,
        t_ref: float | Array = jnp.nan,
        T: float | None = None,
    ) -> tuple[WaveformParams, Array, Array, AmplitudeCoeffs, PhaseCoeffs]:
        """
        Initial processing to compute waveform parameters and time grids.

        Parameters
        ----------
        m1 : float | Array
            Mass of the first black hole in solar masses.
        m2 : float | Array
            Mass of the second black hole in solar masses.
        chi1z : float | Array
            Dimensionless spin of the first black hole along the orbital angular momentum.
        chi2z : float | Array
            Dimensionless spin of the second black hole along the orbital angular momentum.
        distance : float | Array
            Luminosity distance to the binary in megaparsecs.
        phi_ref : float | Array
            Reference phase at frequency f_ref in radians.
        f_ref : float | Array
            Reference frequency in Hz.
        f_min : float | Array
            Minimum frequency in Hz.
        inclination : float | Array
            Inclination angle of the binary in radians.
        psi : float | Array
            Polarization angle in radians.
        delta_t : float | Array, default 15.0
            Time step for waveform generation in seconds.
        t_min : float | Array, default jnp.nan
            Minimum time for waveform generation in seconds. If NaN, will be set by the minimum frequency.
        t_ref : float | Array, default jnp.nan
            Reference time for waveform generation in seconds. If NaN, will be set by the reference frequency.
        T : float | None, default None
            Total observation time in seconds. If sets, it overrides the default value.

        Returns
        -------
        wf_params : WaveformParams
            Waveform parameters of the binary, including derived parameters like total mass, symmetric mass ratio,
            and time arrays.
        times : Array
            Time array in units of mass for waveform generation.
        mask : Array
            Boolean mask indicating valid time points.
        amplitude_coeffs_22 : AmplitudeCoeffs
            Amplitude coefficients for the (2,2) mode.
        phase_coeffs_22 : PhaseCoeffs
            Phase coefficients for the (2,2) mode.
        """

        # throw an error if any of the two spins is larger than 1
        assert jnp.all(
            jnp.abs(jnp.atleast_1d(chi1z)) <= 1
        ), "Spin must be between -1 and 1"
        assert jnp.all(
            jnp.abs(jnp.atleast_1d(chi2z)) <= 1
        ), "Spin must be between -1 and 1"

        wf_params = self._process_parameters(
            m1,
            m2,
            chi1z,
            chi2z,
            distance,
            phi_ref,
            f_ref,
            f_min,
            inclination,
            psi,
            delta_t,
            t_min,
            t_ref,
        )
        wf_params, amplitude_coeffs_22, phase_coeffs_22 = jax.vmap(
            self._compute_coeffs_22
        )(wf_params)

        if T is None:
            T = self.T

        num_steps = int(jnp.ceil(T / delta_t))

        # Lazily initialise the adaptive grid size on first call so that
        # (T, delta_t) are known.  If T or delta_t grow in a later call
        # we update, but only when the new estimate falls into a larger
        # BUCKET_SIZE-bucket — so recompilation is rare and bounded.
        # if self.coarse_grain:
        # compute this even without coarse graining to allow users to extract the adaptive grid size for their own use.
        new_max = estimate_adaptive_steps_from_T(T, delta_t)
        if self.max_adaptive_steps is None or new_max > self.max_adaptive_steps:
            self.max_adaptive_steps = new_max
            logger.debug(
                "Adaptive grid max_steps set to %d (T=%.1f, delta_t=%.1f)",
                self.max_adaptive_steps,
                T,
                delta_t,
            )
        times, times_mask = self.get_time_grids(wf_params, num_steps)

        # store the parameters to access the coarse-grained time array if needed
        self.wf_params = wf_params

        return wf_params, times, times_mask, amplitude_coeffs_22, phase_coeffs_22

    def get_coarse_grained_time_array(self) -> tuple[Array, Array]:
        """
        Get the coarse-grained time array in seconds. This is useful for users who want to use the same time array for other computations.

        Returns
        -------
        times_sec : Array
            Coarse-grained time array in seconds.
        mask : Array
            Boolean mask indicating valid time points.
        """
        if self.wf_params is None:
            raise RuntimeError(
                "Waveform parameters not initialized. Please call compute_amp_phase or compute_polarizations first."
            )

        times_intrinsic, mask = generate_adaptive_grid(
            self.wf_params.eta,
            self.wf_params.Mt_min,
            self.wf_params.Mt_end,
            self.wf_params.Mdelta_t,
            max_steps=self.max_adaptive_steps,
        )

        times_sec = mass_to_second(times_intrinsic, self.wf_params.total_mass)

        return times_sec, mask
